theme: minima
title: Mike's Blog
author: Mike
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 I'm just here to discuss life and all things that ara happening in my life.
 


# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
